{{- $fullname := include "global-one.fullname" . -}}
{{- $labels := include "global-one.labels" . -}}
{{- if .Values.rbac }}
{{- if and .Values.serviceAccount.create .Values.rbac.create -}}
{{- range .Values.rbac.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}-binding
  labels:
    {{- $labels | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullname }}
    namespace: {{ $.Release.Namespace | default "default" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .name }}
{{- end }}
{{- end }}
{{- end }} 