{{- if .Values.configMap }}
{{- range .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- range $key, $path := .fileData }}
  {{ $key }}: |
{{- $file := .Files.Get $path | nindent 4 }}
{{ $file }}
{{- end }}
{{- end }}
{{- end }}
