{{- $fullname := include "global-one.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "global-one.fullname" . }}
  labels:
    {{- include "global-one.labels" . | nindent 4 }}
spec:
  {{- if and .Values.autoscaling (not .Values.autoscaling.enabled) }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "global-one.labels" . | nindent 6 }}
  {{ with .Values.strategy }}
  strategy:
    type: {{ .type | default "RollingUpdate" }}
    {{ with .rollingUpdate }}
    rollingUpdate:
      maxSurge: {{ .maxSurge | default "25%" }}
      maxUnavailable: {{ .maxUnavailable | default "25%" }}
    {{ end }}
  {{ end }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

        {{- if .Values.configMap }}
        checksum/configmap: {{ include (print $.Template.BasePath "/ConfigMap.yaml") . | sha256sum }}
        {{- end }}

      labels:
        {{- include "global-one.labels" . | nindent 8 }}

        {{- with .Values.podLabels }}
        # Include podLabels
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:

      # Connect volumes
      volumes:
        {{- if .Values.configMap }}
        {{- range .Values.configMap }}
        - name: {{ $fullname }}-{{ .name }}
          configMap:
            name: {{ $fullname }}-{{ .name }}
        {{- end }}
        {{- end }}

        {{- with .Values.pvc }}
        {{- range .create }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
        {{ range .connect }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
        {{- end }}

      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if and .Values.serviceAccount .Values.serviceAccount.create }}
      serviceAccountName: {{ include "global-one.fullname" . }}
      {{- end }}

      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.initContainers }}
      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}"
          {{- if .env }}
          env:
            {{- range $name, $value := .env }}
            - name: {{ $name }}
              {{- if (typeOf $value) | eq "string" }}
              value: {{ $value | quote }}
              {{- else if $value.secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secret.name | quote }}
                  key: {{ $value.secret.key | quote }}
                {{- end }}
              {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}

      containers:
        - name: {{ include "global-one.fullname" . }}

          {{ with .Values.lifecycle }}
          lifecycle:
             {{ toYaml . | nindent 12 }}
          {{ end }}

          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          image: {{ include "global-one.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- include "global-one.env" . | nindent 12 }}
          {{- end }}

          volumeMounts:
            {{- with .Values.pvc }}
            {{- range .create }}
            {{- if .mountPath }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- end }}

            {{- range .connect }}
            {{- if .mountPath }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- end }}
            {{- end }}

          {{- with .Values.service }}
          ports:
            {{- range . }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              {{ if .protocol }}
              protocol: {{ .protocol }}
              {{ else }}
              protocol: TCP
              {{ end }}
            {{- end }}
          {{- end }}

          {{- with .Values.healthCheck }}
          #livenessProbe
          {{- if .livenessProbe }}
          {{- if .livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .livenessProbe.periodSeconds | default 20 }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds | default 10 }}
            failureThreshold: {{ .livenessProbe.failureThreshold | default 5 }}
            httpGet:
              {{- if .livenessProbe.path }}
              path: {{ .livenessProbe.path }}
              {{- else }}
              path: {{ .singlePath | default "/" }}
              {{- end }}
              port: {{ .port | default "http" }}
          {{- end }}
          {{- end }}
          #readinessProbe
          {{- if .readinessProbe }}
          {{- if .readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .readinessProbe.periodSeconds | default 20 }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds | default 10 }}
            failureThreshold: {{ .readinessProbe.failureThreshold | default 5 }}
            httpGet:
              {{- if .readinessProbe.path }}
              path: {{ .readinessProbe.path }}
              {{- else }}
              path: {{ .singlePath | default "/" }}
              {{- end }}
              port: {{ .port | default "http" }}
          {{- end }}
          {{- end }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
