apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "global-one.fullname" . }}
  labels:
    {{- include "global-one.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "global-one.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "global-one.selectorLabels" . | nindent 8 }}
      # Include podLabels
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.connectVolume }}
      volumes:
        {{ toYaml .Values.connectVolume | nindent 8 }}
      {{- end }}

      {{- if .Values.initContainers }}
      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}"
          {{- if .env }}
          env:
            {{- range $name, $value := .env }}
            - name: {{ $name }}
              {{- if (typeOf $value) | eq "string" }}
              value: {{ $value | quote }}
              {{- else if $value.secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secret.name | quote }}
                  key: {{ $value.secret.key | quote }}
                {{- end }}
              {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "global-one.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- if .Values.containers }}
      {{- range .Values.containers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- if .command }}
          command:
            {{- toYaml .command | nindent 12 }}
          {{- end }}
          {{- if .args }}
          args:
            {{- toYaml .args | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
            {{- range $name, $value := .env }}
            - name: {{ $name }}
              {{- if (typeOf $value) | eq "string" }}
              value: {{ $value | quote }}
              {{- else if $value.secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secret.name | quote }}
                  key: {{ $value.secret.key | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
      {{- end }}
      {{- else }}
        - name: {{ include "global-one.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.env }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.env }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- else if .Values.image.repository }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              {{- if (typeOf $value) | eq "string" }}
              value: {{ $value | quote }}
              {{- else if $value.secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secret.name | quote }}
                  key: {{ $value.secret.key | quote }}
              {{- end }}
            {{- end }}
          {{- end }}

          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{ toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}

      {{- end }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
          {{- with .Values.healthCheck }}
          {{- if .livenessProbe.enable }}
          livenessProbe:
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
          {{- end }}
          {{- if .readinessProbe.enable }}
          readinessProbe:
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
