{{- $fullName := include "global-one.fullname" . -}}
{{- $labels := include "global-one.labels" . -}}
{{- range $name, $svc := .Values.service }}
  {{- if and $svc.ingress $svc.ingress.enabled }}
    {{- $path := $svc.ingress.path | default "/" -}}
    {{- $pathType := $svc.ingress.pathType | default "Prefix" -}}
    {{- $port := $svc.port -}}
    {{- $hosts := $svc.ingress.hosts | default (list) -}}
    {{- $singleHost := $svc.ingress.host | default "global-one.local" -}}
    {{- $existingSecret := $svc.ingress.existingSecret | default "" -}}
    {{- $existingSecrets := $svc.ingress.existingSecrets | default dict -}}
    {{- $svcName := (ternary (printf "%s-%s" $fullName $name) $fullName (or $svc.separate false)) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $svc.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $svc.ingress.tls }}
  tls:
    {{- if gt (len $hosts) 0 }}
      {{- range $hosts }}
    - hosts:
        - {{ . }}
      {{- if and (hasKey $existingSecrets .) (typeIs "map[string]interface {}" $existingSecrets) }}
      secretName: {{ index $existingSecrets . | quote }}
      {{- else if $existingSecret }}
      secretName: {{ $existingSecret | quote }}
      {{- else }}
      secretName: {{ printf "%s-tls" . }}
      {{- end }}
      {{- end }}
    {{- else }}
    - hosts:
        - {{ $singleHost }}
      {{- if $existingSecret }}
      secretName: {{ $existingSecret | quote }}
      {{- else }}
      secretName: {{ printf "%s-tls" $singleHost }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- if gt (len $hosts) 0 }}
      {{- range $hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $path }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $port }}
      {{- end }}
    {{- else }}
    - host: {{ $singleHost | quote }}
      http:
        paths:
          - path: {{ $path }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $port }}
    {{- end }}

  {{- end }}
{{- end }}