{{- $fullName := include "global-one.fullname" . -}}
{{- $labels := include "global-one.labels" . -}}
{{- range .Values.service }}
{{- if and .ingress .ingress.enabled -}}
{{- $path := .ingress.path | default "/" -}}
{{- $pathType := .ingress.pathType | default "ImplementationSpecific" -}}
{{- $port := .port -}}
{{- $hosts := .ingress.hosts | default (list) -}}
{{- $singleHost := .ingress.host | default "global-one.local" -}}
{{- $existingSecret := .ingress.existingSecret | default "" -}}
{{- $existingSecrets := .ingress.existingSecrets | default dict -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .ingress.tls }}
  tls:
    {{- if gt (len $hosts) 0 }}
    {{- range $hosts }}
    - hosts:
        - {{ . }}
      {{- if and (hasKey $existingSecrets .) (typeIs "map[string]interface {}" $existingSecrets) }}
      secretName: {{ index $existingSecrets . | quote }}
      {{- else if $existingSecret }}
      secretName: {{ $existingSecret | quote }}
      {{- else }}
      secretName: {{ printf "%s-tls" . }}
      {{- end }}
    {{- end }}
    {{- else }}
    - hosts:
        - {{ $singleHost }}
      {{- if $existingSecret }}
      secretName: {{ $existingSecret | quote }}
      {{- else }}
      secretName: {{ printf "%s-tls" $singleHost }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- if gt (len $hosts) 0 }}
    {{- range $hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $path }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $port }}
    {{- end }}
    {{- else }}
    - host: {{ $singleHost | quote }}
      http:
        paths:
          - path: {{ $path }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $port }}
    {{- end }}

{{- end }}
{{- end }}