{{- $useDefaultPolicy := .Values.service.useDefaultPolicy }}
{{- range $index, $port := .Values.service.ports }}
{{- if $port.networkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "global-one.fullname" $ }}-{{ $port.name }}
  labels:
    app.kubernetes.io/name: {{ include "global-one.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "global-one.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  ingress:
    {{- if $useDefaultPolicy }}
    - from:
        - podSelector: {}
          namespaceSelector: {}
      ports:
        - port: {{ $port.port }}
    {{- end }}

    - from:
        {{- range $ip := $port.networkPolicy.ipList }}
        - ipBlock:
            cidr: {{ if not (regexMatch "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+/[0-9]+$" $ip) }}{{ $ip }}/32{{ else }}{{ $ip }}{{ end }}
        {{- end }}
      ports:
        - port: {{ $port.port }}
{{- end }}
{{- end }}
