{{- $fullname := include "global-one.fullname" . -}}
{{- $labels := include "global-one.labels" . -}}

{{- range $name, $svc := .Values.service }}
{{- if and $svc.networkPolicy $svc.networkPolicy.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-{{ $name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- $labels | nindent 6 }}
  policyTypes:
    {{- if $svc.networkPolicy.policyTypes }}
    {{- range $svc.networkPolicy.policyTypes }}
    - {{ . }}
    {{- end }}
    {{- else }}
    - Ingress
    {{- end }}

  ingress:
    {{- if $svc.networkPolicy.ingressAllowAllPods }}
    - from:
        - podSelector: {}
      ports:
        - port: {{ $svc.port }}
          protocol: {{ $svc.protocol | default "TCP" }}
    {{- else }}
    - from:
        {{- if $svc.networkPolicy.allowFromAllNamespaces }}
        - namespaceSelector: {}
        {{- else }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $.Release.Namespace }}
        {{- end }}
      ports:
        - port: {{ $svc.port }}
          protocol: {{ $svc.protocol | default "TCP" }}
    {{- end }}

    {{- if $svc.networkPolicy.ipList }}
    {{- range $ip := $svc.networkPolicy.ipList }}
    - from:
        - ipBlock:
            cidr: {{ if not (regexMatch "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+/[0-9]+$" $ip) }}{{ $ip }}/32{{ else }}{{ $ip }}{{ end }}
      ports:
        - port: {{ $svc.port }}
          protocol: {{ $svc.protocol | default "TCP" }}
    {{- end }}
    {{- end }}

  {{- if or $svc.networkPolicy.egressAllowAllPods $svc.networkPolicy.useDefaultPolicy }}
  egress:
    - to:
        {{- if $svc.networkPolicy.egressAllowAllPods }}
        - podSelector: {}
        {{- else }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $.Release.Namespace }}
        {{- end }}
      ports:
        - port: {{ $svc.port }}
          protocol: {{ $svc.protocol | default "TCP" }}
  {{- end }}

{{- end }}
{{- end }}
