{{- $labels := include "global-one.labels" . -}}

{{- with .Values.pvc }}
{{- range .create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
    {{- $labels | nindent 4 }}
  {{ with .annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- if .accessModes }}
    {{- range .accessModes }}
    - {{ . | quote }}
    {{- end }}
    {{- else }}
    - "ReadWriteOnce"
    {{- end }}
  resources:
    requests:
      storage: {{ default "1Gi" .size | quote }}
  {{- if .storageClassName }}
  storageClassName: "{{ .storageClassName }}"
  {{- end }}
  {{- if .selector }}
  selector:
    matchLabels:
      {{- range $key, $value := .selector.matchLabels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}