{{- $svcType := index .Values.service.type -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "global-one.fullname" . }}
  labels:
    {{- include "global-one.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      {{- if and (or (eq $svcType "LoadBalancer") (eq $svcType "NodePort")) .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "global-one.selectorLabels" . | nindent 4 }}
{{- if .Values.service.headless.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "global-one.fullname" . }}-headless"
  labels:
    {{- include "global-one.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "global-one.selectorLabels" . | nindent 4 }}
{{- end }}
