{{- $fullname := include "global-one.fullname" . -}}
{{- $labels := include "global-one.labels" . -}}
{{- $selectorLabels := include "global-one.selectorLabels" . -}}
{{- $sharedPorts := list }}

{{- if .Values.service }}
{{- range $name, $config := .Values.service }}
  {{- if $config.separate }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: {{ default "ClusterIP" $config.type }}
  {{- if $config.headless }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ $config.port }}
      targetPort: {{ $config.port }}
      protocol: {{ default "TCP" $config.protocol }}
      name: {{ $name }}
      {{- if and (or (eq $config.type "LoadBalancer") (eq $config.type "NodePort")) $config.nodePort }}
      nodePort: {{ $config.nodePort }}
      {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
---
  {{- else }}
    {{- $sharedPort := dict "port" $config.port "targetPort" $config.port "protocol" (default "TCP" $config.protocol) "name" $name "headless" $config.headless }}
    {{- $sharedPorts = append $sharedPorts $sharedPort }}
  {{- end }}
{{- end }}
{{- end }}

{{- if gt (len $sharedPorts) 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: ClusterIP
  {{- if (index $sharedPorts 0).headless }}
  clusterIP: None
  {{- end }}
  ports:
    {{- range $sharedPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
{{- end }}