{{- $fullname := include "global-one.fullname" . -}}
{{- $labels := include "global-one.labels" . -}}
{{- $sharedHeadlessPorts := list }}

{{- range $name, $config := .Values.service }}
  {{- if $config.headless }}
    {{- if $config.separate }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $name }}-headless
  labels:
    {{- $labels | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ $config.port }}
      targetPort: {{ $config.port }}
      protocol: {{ default "TCP" $config.protocol }}
      name: {{ $name }}
  selector:
    {{- $labels | nindent 4 }}
---
    {{- else }}
      {{- $sharedHeadlessPort := dict "port" $config.port "targetPort" $config.port "protocol" (default "TCP" $config.protocol) "name" $name }}
      {{- $sharedHeadlessPorts = append $sharedHeadlessPorts $sharedHeadlessPort }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if gt (len $sharedHeadlessPorts) 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-headless
  labels:
    {{- $labels | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range $sharedHeadlessPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- $labels | nindent 4 }}
{{- end }}