{{- $fullname := include "global-one.fullname" . -}}
{{- $labels := include "global-one.labels" . -}}
{{- $sharedPorts := list }}

{{- range .Values.service }}
{{- $type := default "ClusterIP" .type }}
{{- if or .separate (not (eq $type "ClusterIP")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ .name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ default "TCP" .protocol }}
      name: {{ .name }}
      {{- if and (or (eq $type "LoadBalancer") (eq $type "NodePort")) .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
  selector:
    {{- $labels | nindent 4 }}
---
{{- else }}
{{- $sharedPorts = append $sharedPorts (dict "port" .port "targetPort" .name "protocol" (default "TCP" .protocol) "name" .name) }}
{{- end }}
{{- end }}

{{- if gt (len $sharedPorts) 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range $sharedPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- $labels | nindent 4 }}
{{- end }}