variables:
  # Registry
  #  REGISTRY: registry.gitlab.com
  #  IMAGE_NAME: image_service_name
  #  IMAGE_ENV: dev

  # with gitlab env
  IMAGE_TAG: latest-${CI_COMMIT_SHORT_SHA}

  # Docker
  DOCKERFILE_PATH: ./Dockerfile

.build_and_push:
  stage: build
  services: [ docker:dind ]
  script:
    - | # Create docker image
      if [ -z ${IMAGE_ENV} ]; then
        docker build -f ${DOCKERFILE_PATH} -t ${REGISTRY}/${IMAGE_NAME} .
      else
        docker build -f ${DOCKERFILE_PATH} -t ${REGISTRY}/${IMAGE_ENV}/${IMAGE_NAME} .
      fi
    - | # Docker tag
      if [ -z ${IMAGE_ENV} ]; then
        docker tag ${REGISTRY}/${IMAGE_NAME}:latest ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
      else
        docker tag ${REGISTRY}/${IMAGE_ENV}/${IMAGE_NAME}:latest ${REGISTRY}/${IMAGE_ENV}/${IMAGE_NAME}:${IMAGE_TAG}
      fi
    - | # Push image
      if [ -z ${IMAGE_ENV} ]; then
        docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} && \
        docker push ${REGISTRY}/${IMAGE_NAME}:latest
      else
        docker push ${REGISTRY}/${IMAGE_ENV}/${IMAGE_NAME}:${IMAGE_TAG} && \
        docker push ${REGISTRY}/${IMAGE_ENV}/${IMAGE_NAME}:latest
      fi
