{{/*{{- $fullname := include "global-one.fullname" . -}}*/}}
{{/*{{- $labels := include "global-one.labels" . -}}*/}}

{{/*{{- range .Values.service }}*/}}
{{/*{{- $serviceName := .name -}}*/}}
{{/*{{ with .istio }}*/}}
{{/*{{ range .gateway }}*/}}
{{/*apiVersion: networking.istio.io/v1beta1*/}}
{{/*kind: Gateway*/}}
{{/*metadata:*/}}
{{/*  name: {{ $fullname }}-{{ $serviceName }}*/}}
{{/*  labels:*/}}
{{/*    {{- $labels | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  selector:*/}}
{{/*    istio: ingressgateway*/}}
{{/*  servers:*/}}
{{/*    {{- range .servers }}*/}}
{{/*    - port:*/}}
{{/*        number: {{ .port }}*/}}
{{/*        name: {{ .name }}*/}}
{{/*        protocol: {{ .protocol }}*/}}
{{/*      hosts:*/}}
{{/*        {{- toYaml .hosts | nindent 6 }}*/}}
{{/*      {{- if .tls }}*/}}
{{/*      tls:*/}}
{{/*        credentialName: {{ .tls.credentialName }}*/}}
{{/*        mode: {{ .tls.mode }}*/}}
{{/*      {{- end }}*/}}
{{/*    {{- end }}*/}}
{{/*---*/}}
{{/*{{ end }}*/}}
{{/*{{ end }}*/}}
{{/*{{- end }}*/}}
