templates:
  common: &common
    chart: oci://registry-1.docker.io/mrmerseri/global-one
    version: 0.1.3
    hooks:
      - events: [ "prepare" ]
        command: "sh"
        args: [ "./scripts/get-values-hook.sh", "{{ .Namespace }}", "{{`{{ .Release.Name }}`}}" ]
      - events: ["cleanup"]
        command: "sh"
        args: ["-c", "rm -f temp-values.yaml"]
    values:
      - values/services/{{`{{ .Release.Name }}`}}/values.yaml
      - values/services/{{`{{ .Release.Name }}`}}/{{ .Environment.Name }}.yaml
      {{- if or (eq .Environment.Name "dev1") (eq .Environment.Name "dev2") (eq .Environment.Name "dev3") (eq .Environment.Name "dev4") }}
      - values/services/{{`{{ .Release.Name }}`}}/dev.yaml
      {{- end }}

releases:
  - name: node-test
    <<: *common
    installed: {{ or
      (eq .Environment.Name "test")
      (eq .Environment.Name "hotfix")
      (eq .Environment.Name "dev1")
      (eq .Environment.Name "dev2")
      (eq .Environment.Name "dev3")
      (eq .Environment.Name "dev4")
    }}

---

environments:
  prod: {}
  dev: {}
  dev1: {}
  dev2: {}
  dev3: {}
  dev4: {}