templates:
  common: &common
    chart: oci://registry-1.docker.io/mrmerseri/global-one
    version: 0.1.5
    values:
      - values/services/{{`{{ .Release.Name }}`}}/values.yaml
      # if need specific Environment
      - values/services/{{`{{ .Release.Name }}`}}/{{ .Environment.Name }}.yaml
      # if need specific values
      {{- if or (eq .Environment.Name "dev1") (eq .Environment.Name "dev2") (eq .Environment.Name "dev3") (eq .Environment.Name "dev4") }}
      - values/services/{{`{{ .Release.Name }}`}}/dev.yaml
      {{- end }}

releases:
  - name: node-test
    <<: *common
    # if need specific installed
    installed: {{ or
      (eq .Environment.Name "test")
      (eq .Environment.Name "hotfix")
      (eq .Environment.Name "dev1")
      (eq .Environment.Name "dev2")
      (eq .Environment.Name "dev3")
      (eq .Environment.Name "dev4")
    }}

---
# if need specific Environment
environments:
  prod: {}
  dev: {}
  dev1: {}
  dev2: {}
  dev3: {}
  dev4: {}