environments:
  prod: {}
  dev: {}
---
repositories:
  - name: global-one
    url: registry-1.docker.io/mrmerseri
    oci: true
---
releases:
  - name: node-test
    chart: global-one/global-one
    version: 0.1.0
    values:
      - values/values.yaml
      - values/{{ .Environment.Name }}.yaml

